services:
  mongodb:
    image: mongo:7.0
    container_name: pokemon-db
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
